[package]
name = "qulacs-bridge"
version = "0.1.0"
edition = "2021"

[features]
default = []
num = ["dep:num"]

[dependencies]
cxx = "1.0.148"
num = { version = "0.4.3", optional = true }

[build-dependencies]
cxx-build = "1.0.148"
pkg-config = "0.3.32"

[dev-dependencies]
rand = "0.9.0"
