name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main  
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Build
      shell: devenv shell
      run: cargo build --verbose
    - name: Run tests
      shell: devenv shell
      run: cargo test --verbose
