name: Release Plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build Qulacs
        run: |
          wget -qO- https://github.com/qulacs/qulacs/archive/refs/tags/v0.6.11.tar.gz | gunzip | tar xvf -
          mkdir third_party/
          mv qulacs-0.6.11 third_party/qulacs/
          cd third_party/qulacs
          bash ./script/build_gcc.sh
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          LIBQULACS_PATH: ./third_party/qulacs/build
